[FrameworkBundle] Implemented ChainCacheClearer service
massimilianobraglia/jymfony pull request #1
Opened 2017-08-04 13:20 UTC by giovannialbero1992

integration for (https://github.com/jymfony/jymfony/pull/11)

2017-08-04 13:33 UTC, massimilianobraglia requested changes

2017-08-04 13:33 UTC, massimilianobraglia commented on src/Component/Kernel/src/CacheClearer/CacheClearerInterface.js
> +     * @param {String} cacheDir
jsdoc type string is with the initial 's' in lowercase

2017-08-04 13:33 UTC, massimilianobraglia commented on src/Component/Kernel/src/CacheClearer/ChainCacheClearer.js
> +     * @param {[Jymfony.Component.Kernel.CacheClearer.CacheClearerInterface} clearers
remove wrongly opened '['

2017-08-04 13:33 UTC, massimilianobraglia commented on src/Component/Kernel/src/CacheClearer/ChainCacheClearer.js
> +     *
remove empty comment line

2017-08-04 13:37 UTC, giovannialbero1992 commented on src/Component/Kernel/src/CacheClearer/ChainCacheClearer.js
> +     * @param {[Jymfony.Component.Kernel.CacheClearer.CacheClearerInterface} clearers
In this case is missed a ']' because the argument is an array.

2017-08-04 13:47 UTC, massimilianobraglia commented on src/Component/Kernel/src/CacheClearer/ChainCacheClearer.js
> +     * @param {[Jymfony.Component.Kernel.CacheClearer.CacheClearerInterface} clearers
👍

2018-03-13 08:58 UTC, merged

2018-03-13 08:58 UTC, massimilianobraglia commented
@giovannialbero1992 FINALLY, it is merged 😄

2018-03-13 09:08 UTC, giovannialbero1992 commented
Great @massimilianobraglia